# Generated by Django 4.2.6 on 2023-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('opcoes', models.CharField(choices=[('Unidade de Placa de Carro', 'Unidade de Placa de Carro'), ('Par de Placa de Carro', 'Par de Placa de Carro'), ('Placa de Moto', 'Placa de Moto')], max_length=100)),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
        ),
    ]
